#!/bin/bash

#Fix for Sourcetree
export PATH=/usr/local/bin:$PATH

if which swiftformat >/dev/null; then
  git diff --diff-filter=d --staged --name-only | grep -e '\(.*\).swift$' | while read line; do
    swiftformat "${line}";
    git add "$line";
  done
else
  echo "Missing SwiftFormat see .swiftformat file"
fi
